/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Legacy palette (still available if used elsewhere)
        'dark-green': '#2A3C2D',
        'purple': '#580695',
        'light-purple': '#900AF5',
        'dark-gray': '#868686',
        'gray': '#D9D9D9',
        'light-gray': '#F7F5EC',
        'black': '#1E1E1E',
        'yellow': '#D4AF37',
        'brand-blue': '#002455',
        'brand-blue-dark': '#050E3C',
        primary: {
          50: '#F7F5EC',
          100: '#E8E5D6',
          200: '#D9D9D9',
          300: '#868686',
          400: '#2A3C2D',
          500: '#580695',
          600: '#900AF5',
          700: '#D4AF37',
          800: '#1E1E1E',
          900: '#050E3C',
        },
        // Stitch design tokens
        'surface-dim': '#d9dadb',
        'secondary': '#006b5f',
        'on-error-container': '#93000a',
        'outline': '#727785',
        'primary-fixed-dim': '#b8c9dc',
        'inverse-on-surface': '#f0f1f2',
        'on-tertiary-fixed': '#410003',
        'on-surface': '#191c1d',
        'on-tertiary-container': '#ffffff',
        'tertiary-container': '#dd3635',
        'on-secondary-fixed': '#00201c',
        'on-background': '#191c1d',
        'on-tertiary-fixed-variant': '#930010',
        'secondary-fixed': '#8df5e4',
        'inverse-surface': '#2e3132',
        'tertiary-fixed-dim': '#ffb3ac',
        'surface-container-highest': '#e1e3e4',
        'on-primary-fixed': '#001a41',
        'surface': '#f8f9fa',
        'error': '#ba1a1a',
        'primary': '#002455',
        'tertiary': '#b91a20',
        'on-primary': '#ffffff',
        'inverse-primary': '#b8c9dc',
        'surface-container': '#edeeef',
        'on-primary-container': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'on-secondary-container': '#007165',
        'on-error': '#ffffff',
        'on-secondary': '#ffffff',
        'background': '#f8f9fa',
        'surface-container-lowest': '#ffffff',
        'secondary-container': '#8df5e4',
        'on-tertiary': '#ffffff',
        'surface-bright': '#f8f9fa',
        'tertiary-fixed': '#ffdad6',
        'secondary-fixed-dim': '#70d8c8',
        'surface-container-high': '#e7e8e9',
        'on-surface-variant': '#414754',
        'surface-variant': '#e1e3e4',
        'on-secondary-fixed-variant': '#005048',
        'error-container': '#ffdad6',
        'on-primary-fixed-variant': '#002455',
        'surface-tint': '#002455',
        'outline-variant': '#c1c6d6',
        'primary-container': '#0a3d6b',
        'primary-fixed': '#e4eaf2',
      },
      fontFamily: {
        sans: ['SF Pro Text', 'system-ui', '-apple-system', 'sans-serif'],
      },
      letterSpacing: {
        'tighter': '-0.03em',
        'tight': '-0.01em',
        'normal': '0',
        'wide': '0.02em',
        'wider': '0.05em',
      },
      animation: {
        'fade-in': 'fadeIn 0.6s ease-out forwards',
        'slide-up': 'slideUp 0.6s ease-out forwards',
        'slide-down': 'slideDown 0.6s ease-out forwards',
        'scale-in': 'scaleIn 0.4s ease-out forwards',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideDown: {
          '0%': { opacity: '0', transform: 'translateY(-30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
      },
    },
  },
  plugins: [],
}
